apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-01oj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-01oj
    app.kubernetes.io/part-of: integ-app-yhls
  name: hacbs-test-project-01oj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-01oj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-01oj
    spec:
      containers:
      - image: quay.io/bootstrap/integration1-ohpz-tenant/integ-app-yhls/hacbs-test-project-01oj@sha256:04c975b3766a1ccb01784043ad6789dff54b52810d7502f063f68d248750b173
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
